title: Memories of Two Cities
title-abbreviated: Memories of Two Cities
description: >- # this means to ignore newlines until "baseurl:"
  "‘Memories of Two Cities’ is a pictorial exhibition jointly presented by the Capital Library of China and the National Library of Singapore, signifying the goodwill and partnership between the two institutions."
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Resource Room and Pagination
paginate: 12

# Homepage sections
homepage_hero_i_want_to: false
homepage_resources: true

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"

exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]

collections:
  tropical-metropolis:
    output: true
  left-nav-two:
    output: true
  high-life-in-the-city:
    output: true
  away-from-the-bustle:
    output: true
  memories-of-two-cities-singapore:
    output: true
  all-walks-of-life:
    output: true
  places-of-power-and-worship:
    output: true
  a-city-in-motion:
    output: true
  centres-of-commerce:
    output: true
  colourful-customs:
    output: true
